UCLH-Foundry/FlowEHR

- .devcontainer/Dockerfile
Fixes #25 
Shellcheck requires different architecture names than what dpkg produces. Have amended so that amd64 = x86_64
> Fix devcontainer for amd64

- infrastructure/terragrunt.hcl
Fixes occasional AML lagging resource destruction interrupting `make destroy`.
Resolves #7
> Fix fail to destroy

- .github/workflows/devcontainer_make_command.yml
Pass in ORG_GH_TOKEN to Github action env to be able to consume it within the action
Part of the fix for https://github.com/UCLH-Foundry/FlowEHR/issues/100
> Pass in ORG_GH_TOKEN to Github action env

- .gitignore
- Makefile
- README.md
- apps/.terraform.lock.hcl
- apps/README.md
- apps/app/platform.tf
- apps/app/repository.tf
- apps/app/variables.tf
- apps/apps.sample.yaml
- apps/main.tf
- apps/terragrunt.hcl
- apps/variables.tf
- config.sample.yaml
- config_schema.json
- infrastructure/ci-auth/.terraform.lock.hcl
- infrastructure/core/.terraform.lock.hcl
- infrastructure/serve/.terraform.lock.hcl
- infrastructure/transform/.terraform.lock.hcl
- scripts/load_env.sh
- terragrunt.hcl
Resolves #73 
Resolves #74 
Resolves #72 
This PR creates all the required resources for an app being hosted within a managed GitHub repo on `make apps`
Consists of:
> Provision per-app gh resources

- scripts/pipeline_repo_checkout.sh
In https://github.com/UCLH-Foundry/FlowEHR/pull/127  we changed the logic for pulling pipeline repos to run `git pull` on an existing checked out repo, but it looks like it doesn't work in certain git configurations. 
Skipping this step altogether and just leaving code there if it already exists to support local iteration
> Skip pulling repo if already there

- Makefile
Fixing bug introduced in https://github.com/UCLH-Foundry/FlowEHR/pull/127: artifacts aren't being built as part of `make infrastructure-transform`
> Fix Makefile command building artifacts

- .devcontainer/devcontainer.json
Add datafactory as an extension to the devcontainer.
As I understand it (?), the devcontainer is being built from the main branch now, so this needs to go in before the PR where it is actually needed: https://github.com/UCLH-Foundry/FlowEHR/pull/156
> Add datafactory as an extension to the devcontainer

- .github/workflows/devcontainer_make_command.yml
Unblocks https://github.com/UCLH-Foundry/FlowEHR/issues/54  by fixing a bug with datasources not being passed in to the make command.
> Fix datasources not being passed in

- .github/workflows/deploy_infra_test.yml
- .github/workflows/destroy_infra_test.yml
See: https://docs.github.com/en/actions/using-jobs/using-concurrency
> Add concurrency blocks to infra-test CI workflows

- .github/workflows/devcontainer_make_command.yml
- apps/terragrunt.hcl
Adds a fix for the devcontainer make commands treating the pem cert as multiple env vars
Also makes app cert optional in line with potential customers only deploying transform / serve without apps
> Add gh cert in optional dev container env args

- infrastructure/transform/databricks-udr-ips.yaml
- infrastructure/transform/databricks.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/network.tf
This (hopefully) fixes the repeated issues we've seen when trying to deploy clusters. Following some investigation with the help of a support engineer, the reason why we might be seeing this only in the uksouth region currently is because each region has different IPs for various dependencies Databricks relies on and the routing might be clashing with other resources we have set up.
As per https://learn.microsoft.com/en-gb/azure/databricks/administration-guide/cloud-configurations/azure/udr?WT.mc_id=Portal-Microsoft_Azure_Support#--configure-user-defined-routes-with-azure-service-tags I've added a routing table with some service tags for these dependencies to ensure the routing happens correctly each time.
In my testing I've encountered no issues in uksouth however only time will tell.
> Dbks potential cluster bootstrap fix

- config.sample.yaml
This places the missing YAML header `---` into the `config.sample.yaml` file.
> Add correct header to YAML file

- infrastructure/serve/app_service.tf
For some ~stupid~ curious reason, the autoscale settings for the service ASP has started failing with `UnsupportedMetric` for `CpuPercentage`: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4676785741/jobs/8283516301#step:9:4664
I've double checked the docs and this is indeed the correct metric for app service autoscale. To try and resolve this, I'm explicitly setting the `metric_namespace` which is optional and should be derived from the resource id, to see if this fixes it.
> Fix ASP autoscale unsupported metric error

- .github/workflows/devcontainer_make_command.yml
- Makefile
- README.md
- apps/.terraform.lock.hcl
- apps/main.tf
- apps/terragrunt.hcl
- apps/variables.tf
- auth/.terraform.lock.hcl
- infrastructure/core/.terraform.lock.hcl
- infrastructure/core/locals.tf
- infrastructure/core/network.tf
- infrastructure/core/outputs.tf
- infrastructure/serve/terragrunt.hcl
- infrastructure/transform/databricks.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/network.tf
- infrastructure/transform/terragrunt.hcl
- infrastructure/transform/variables.tf
- shared.hcl
- Adds flowehr prefix to tf state
- To differentiate different projects in the state storage (i.e. FlowEHR, Data sources, TRE ...), this adds a prefix to the remote state block - resolves #251
- `make all` command works without having any apps defined (by making the serve block optional unless an app is present in the apps.yaml)
- `make all` now calls `transform-artifacts` - resolves #249 
- Makes data sources `dns_zones` optional
- If `private_dns_zones_rg` is defined, data source dns zone linking will look in that rg instead for existing zones to link to. Resolves #250
> Add flowehr prefix to state & dns zone + makefile fix

- .github/workflows/clean_state.yml
Clean-up currently fails due to soft-delete being enabled on the storage account and cli `storage fs` commands only working for non-soft-delete accounts. We need to use an alternate method for cleaning state.
- Use the `storage blob delete-batch` command which works with soft-delete storage accounts
- Use a pattern for the subfolders to delete
- Removes unnecessary `--yes` flag from acr untag
Tested and successful in my private fork:
> Fix cleanup step

- infrastructure/core/groups.tf
Data scientists + developers AD groups were named with `suffix_override` which was ok for transient builds but blank in persistent builds. Moves to `naming_suffix` instead.
> Fix for AD group names in persistent environments

- .github/workflows/devcontainer_make_command.yml
Adds an optional input to the deploy workflow which can be used to override a repository scoped CI_GITHUB_RUNNER_LABEL. This is required if this workflow is going to be run on different runners within the same repository.  Sadly using a envrionment scoped `vars.CI_GITHUB_RUNNER_LABEL` doesn't work in the runs-on section
> Add optional runner_label input

- apps/README.md
Fix for issue we're facing on private UCLH fork when deploying a private app
Requests to the deployment environments API require `actions: read-only` scopes for GitHub Apps when querying private repos, which is why it's worked for public. The knock-on effect was causing the GitHub TF provider to crash, which is a bad error handling bug that ive raised an issue on the provide for.
> Add missing actions:read scope to GH App scopes

- infrastructure/transform/pipeline.tf
Trigger resource needs to have dependency on pipeline otherwise it can error our depending on timing.
> Add missing Data Factory Trigger TF dependency

- infrastructure/core/outputs.tf
Fixes the outputs with `accesses_real_data = true`
Needs to be an empty string not `null` so terragrunt doesn't complain. Have tested locally and works
> Fix outputs when no group created

- infrastructure/transform/feature-data-store.tf
For the feature store sql server, Public networking should only be disabled when `accesses_real_data` is true so that it can be accessed locally for development in `app-dev` and other synthetic environments
> Synth sql access for local devs

- apps/app/variables.tf
- apps/terragrunt.hcl
- apps/variables.tf
Fixes a bug where more than one app being defined causes terraform to fail parsing into a map.
- Moves the object type definition into the parent variables.tf which allows Terraform to convert the object into a map of objects correctly
> Fix multiple app config parsing bug (move app config type definition to parent module)

- apps/app/data.tf
- apps/app/webapp.tf
- infrastructure/serve/.terraform.lock.hcl
This fixes an issue where TF is trying to look up app contributor users in AD when `var.accesses_real_data` is true, when it doesn't need to (as we don't add anyone to a group to access data locally when the data is real. They may not exist in a prod tenant thus this can break deployments (and has).
> Only look up contributor ad ids if needed

- infrastructure/core/groups.tf
- infrastructure/core/outputs.tf
- infrastructure/serve/aml.tf
- infrastructure/serve/terragrunt.hcl
- infrastructure/serve/variables.tf
- infrastructure/transform/feature-data-store.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/outputs.tf
- infrastructure/transform/terragrunt.hcl
- infrastructure/transform/variables.tf
Apps can read the feature store, but they also need to be able to pull from the model registry. This adds a read-only role definition, and grants apps access to it.
> Allow apps to read model registry

- .github/workflows/auto_labels.yml
Adds a simple GH workflow to add the `needs: triage` label to new issues
> Add auto-labelling workflow

- apps/variables.tf
- infrastructure/transform/databricks.tf
- infrastructure/transform/datalake/connections.tf
- infrastructure/transform/datalake/variables.tf
- infrastructure/transform/feature-data-store.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/main.tf
Fixing the bug #316 by making sure the two service principals used to authenticate from Databricks have a different name. 
Additionally, fixing the `local-exec` swallowing errors when creating the users.
Additionally, fixing https://github.com/UCLH-Foundry/FlowEHR/issues/309 as a drive-by.
Additionally, fixing a dependency issue between Databricks workspace resource and `databricks_spark_version`. 
In https://github.com/UCLH-Foundry/FlowEHR/pull/310, a bug was introduced: two service principals with the same name were created:
Because of this, `create_sql_user.py` script was silently failing: it could not pick between two service principals with the same name when creating a user from an AAD account: 
Additionally, the `local-exec` block that was executing the script was not failing in …
> Fix bug: two service principals with the same name

- config.infra-test.yaml
- config.sample.yaml
- infrastructure/transform/adf.tf
- infrastructure/transform/databricks.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/secrets.tf
- infrastructure/transform/variables.tf
Extract Spark configuration and libraries into a separate section of the config.
- Add `spark_config` section to the config and move the single-node configuration there 
- Add `databricks_libraries` section to the config and propagate all types of libraries supported by databricks terraform provider: https://registry.terraform.io/providers/databricks/databricks/0.4.2/docs/resources/cluster#library-configuration-block 
- Add `databricks_cluster` section to be able to configure the size of the cluster
- Add `init_scripts` section to the config and upload a dbfs file from local filesystem
- Add `databricks_secrets` section to the config and create corresponding secrets in the secret scope
> Extract Spark configuration, secrets, init_scripts and libraries into the config

- config.sample.yaml
- infrastructure/transform/databricks.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/variables.tf
Previously when adding an `autoscale` block and specifying a number of workers, the custom tags for single node were preventing autoscaling from happening, meaning you could not actually customise the cluster node number. This restriction has been removed.
- Added a `num_of_workers` field to the transform config allowing fixed sizes to be specified as well as `0` for `singleNode` mode
- If `0` is specified, we add the necessary spark config and custom tags automatically
- If `autoscale` is specified, any `num_of_workers` setting is ignored and the cluster is configured with autoscale enabled (without the singleNode custom tag as was previously set regardless)
- Also added ability to set `runtime_engine` to either `STANDARD` or `PHOTON` for performance boost
> Databricks cluster customisation: Add singleNode mode and fixed node options

- infrastructure/transform/auth.tf
- infrastructure/transform/databricks.tf
- infrastructure/transform/feature-data-store.tf
- infrastructure/transform/locals.tf
- infrastructure/transform/secrets.tf
Adds a new AAD app, `flowehr-external-${suffix}`, that is used to connect FlowEHR with downstream systems.
The specific way we want to use this app is to assign it roles to resources in TRE workspaces, so that Databricks Pipelines can use credentials from this one single app, rather than having to manipulate credential per each workspace and resource.
- Added a new AAD app, flowehr_external_connection, added corresponding service principal and a secret
- Create secrets in Databricks for this app
- Push the secrets to keyvault
- Refactor all AAD apps in Transform to live in auth.tf file
> Add AAD app for external connections

- infrastructure/transform/unity-catalog-metastore/metastore.tf
- infrastructure/transform/unity-catalog/network.tf
Fixes the DNS mismatch causing storage communication errors
> Fixed mismatch of DNS zones for unity metastore private links

- config.sample.yaml
During the unity catalog deployment it appears that we get inconsistencies if the zone names have capital letters in them. This updates the sample to recommend lower case names.
> Config.Sample Note

- infrastructure/transform/databricks.tf
- infrastructure/transform/secrets.tf
Found `azure-tenant-id` was expected in pipeline code, but missing from databricks secrets. This adds it in.
> Added missing azure-tenant-id secret to databricks

- .devcontainer/devcontainer.json
- infrastructure/transform/locals.tf
- infrastructure/transform/monitoring.tf
Small refactoring: Rename pre-defined metric expected in the dashboard from `rows_inserted` to `rows_updated` to reflect that rows can be inserted, updated and deleted.
> Rename predefined metric
