Makefile
Fixes #23 
Adds `run-all` commands to all deploy make commands
=> Use run-all for tf modules

.github/scripts/build.js, .github/workflows/pr_bot.yml, scripts/name_prefix.py
=> Add action comment for destroy

.github/workflows/devcontainer_make_command.yml, .github/workflows/pr_bot.yml, README.md, config.sample.yaml, config_schema.json, infrastructure/core/main.tf, infrastructure/core/variables.tf, infrastructure/serve/main.tf, infrastructure/serve/variables.tf, infrastructure/terragrunt.hcl, infrastructure/transform/main.tf, infrastructure/transform/variables.tf, scripts/destroy_no_terraform.sh, scripts/load_env.sh, scripts/name_suffix.py
=> Remove underscores in adf name and change prefix -> suffix

infrastructure/core/main.tf, infrastructure/core/outputs.tf, infrastructure/terragrunt.hcl, infrastructure/transform/main.tf, infrastructure/transform/terragrunt.hcl, infrastructure/transform/variables.tf
Resolves #33 
- Managed virtual network for Databricks with secure cluster connectivity
- Managed virtual network for ADF
- Vnet integration for KeyVault
- ADF Linked service configuration for KeyVault
- Databricks secrets scope integration with KeyVault
- Remove unnecessary Databricks provider from core and serve modules
=> Vnet integration for ADF, KV & Databricks

infrastructure/transform/terragrunt.hcl
Add workspace id to provider so it will work when MSI is enabled
=> Fix Databricks TF provider in CI

.github/workflows/pr_checks.yml
Looks like we [hit the rate limit](https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4139014119/jobs/7156111039#step:5:98) in #57 again. Maybe this fixes it(?)
Suggested in: https://github.com/terraform-linters/setup-tflint/issues/143
=> Init tflint with GH token

.devcontainer/devcontainer.json
Until https://github.com/UCLH-Foundry/FlowEHR/issues/100 is fixed, temporarily disable cloning pipeline repos in devcontainer build to unblock CI on main and PR builds.
=> Temporarily disable pipeline_repo_checkout

.github/workflows/pr_bot.yml
=> Add devcontainer test path

infrastructure/transform/network.tf
=> Truncate peer names

.devcontainer/devcontainer.json
=> Assume dir in postCreate

.github/workflows/deploy_infra_test.yml, .github/workflows/destroy_infra_test.yml, .github/workflows/pr_bot.yml, README.md, config.yaml
Changes the public environment name to lowercase `infra-test`, and updates id to `flowehr`
=> Rename env name

.github/workflows/devcontainer_make_command.yml, scripts/retry.sh
See https://github.com/t-young31/FlowEHR/actions/runs/4466492528/jobs/7844752612#step:3:29
=> Run destroy no tf PR command on first CI job

Makefile, apps/README.md, apps/app/acr.tf, apps/app/github-repository.tf, apps/app/locals.tf, apps/app/variables.tf, apps/app/webapp.tf, apps/main.tf, apps/terragrunt.hcl, apps/variables.tf
- Fixes an issue where having no app.{ENVIRONMENT}.yaml when deploying causes a null iterator error
- Adds a PR suffix to an app_id if suffix_override is specified, to fix conflicts with existing apps in PR environments
=> App ci fixes

.github/workflows/devcontainer_make_command.yml
=> Fix ACR cleanup on CI

scripts/sql/create_sql_user.py
Actually works towards Innovator Workspace in TRE, and should allow app connectivity for developers.
Issue seems to be that the AAD groups are given `LOGIN`s to the server, and are made `USER`s on the feature database - but when a user in a group connects, they get a cryptic SQL auth error. Having been through all debugging for connectivity, groups, nested groups, and guest users - it appears that the group needs to 'exist' in the master db, as well as the target DB - even though they don't need any permissions to `master`. Existing there allows the 'generic' connection to the server that we want.
=> Add SQL groups to master DB, without permissions

CIS-Adherence.md, infrastructure/core/main.tf, infrastructure/serve/main.tf
Adds configuration to the two FlowEHR storage accounts for CIS compliance.
=> CIS compliance: storage

CIS-Adherence.md, config.sample.yaml, infrastructure/core/main.tf, infrastructure/core/network.tf, infrastructure/core/variables.tf, infrastructure/serve/main.tf
Adds NSG for vnet + network watcher logs if it's defined in the root config
=> CIS compliance: logging

.devcontainer/devcontainer.json, .github/workflows/devcontainer_make_command.yml, terragrunt.hcl
Using resolves in the loosest possible sense this PR adds a couple of regex patterns for which an retries usually fix the error. Docs: https://terragrunt.gruntwork.io/docs/features/auto-retry/
=> Add terragrunt auto-retrys

apps/app/github-environment.tf
Required change for https://github.com/UCLH-Foundry/Dash-Seedling/pull/11
=> Alter required checks for new required workflow

apps/app/cosmos.tf
Creating new cosmos container 
- Added resource block to add new cosmos container
=> Add cosmos container

apps/app/aad_app/locals.tf, apps/app/github-environment.tf
Added a missing GH environment secret that we need for the AAD authentication for the UI and API FlowEHR apps.
=> Added tenant id to GH env
